--CREATE PARTITION FUNCTION 

CREATE PARTITION FUNCTION CUST_PART_FUN (INT)
AS RANGE RIGHT
FOR VALUES (1000,2000,3000,4000,5000)


-- CREATE PARTITION SCHEME 

CREATE PARTITION SCHEME CUST_PART_SCH AS PARTITION CUST_PART_FUN TO (FG1,FG2,FG3,FG4,FG5,FG6)


-- CREATE TABLE 

CREATE TABLE SIMPLEPARTITION (

EMP_ID INT IDENTITY(1,1) NOT NULL,
EMPDATE DATETIME NULL
) ON CUST_PART_SCH (EMP_ID)

DECLARE @I INT 
SET @I = 0
WHILE @I <5000
BEGIN 

INSERT INTO SIMPLEPARTITION (EMPDATE) VALUES (GETDATE())

SET @I =  @I + 1

END 
SELECT * FROM SIMPLEPARTITION


SELECT $PARTITION.CUST_PART_FUN(EMP_ID) AS 'PARTITION_NUMBER', * FROM [SIMPLEPARTITION]
