-- SAMPLE TABLE VALUED FUNCTION ON PERSON.AddressType TABLE [ADVENTUREWORKS2017]

CREATE FUNCTION TVF_NEW (@PARAM INT)

RETURNS TABLE AS

RETURN SELECT * FROM PERSON.AddressType WHERE AddressTypeID= @PARAM

SELECT * FROM DBO.TVF_NEW (1)

-- DROP FUNCTION TVF_NEW

-- SAMPLE SCALAR FUNCTION TO RETURN DOB

CREATE FUNCTION UDF_DOB (@PARAM VARCHAR(10))

RETURNS VARCHAR(10) AS 

BEGIN

DECLARE @DOB INT

SET @DOB =  CAST(DATEPART(YY,GETDATE()) AS INT) - CAST(DATEPART(YY,@PARAM) AS INT)

RETURN @DOB

END

SELECT DBO.UDF_DOB ('1993')

--DROP FUNCTION UDF_DOB


--SCLAR FUNCTION FOR DOB IN YYYYMMDD

CREATE FUNCTION UDF_DOB (@PARAM DATETIME)

RETURNS VARCHAR(10) AS 

BEGIN 

DECLARE @DOB VARCHAR(10)
DECLARE @YYYY CHAR(1) = 'Y'
DECLARE @MM CHAR(1) = 'M'
DECLARE @DD CHAR(1) = 'D'

SET @DOB =  CONCAT(DATEPART(YY,GETDATE())  - DATEPART(YY,@PARAM),@YYYY,DATEPART(MM,GETDATE())  - DATEPART(MM,@PARAM),@MM,
ABS(DATEPART(DD,GETDATE())  - DATEPART(DD,@PARAM)),@DD)

RETURN @DOB

END

SELECT DBO.UDF_DOB ('1993-04-27 00:00:00.000')

--DROP FUNCTION UDF_DOB